<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AppContext\**" />
    <Compile Remove="Functional\**" />
    <Compile Remove="Mediator\**" />
    <Compile Remove="Results\**" />
    <EmbeddedResource Remove="AppContext\**" />
    <EmbeddedResource Remove="Functional\**" />
    <EmbeddedResource Remove="Mediator\**" />
    <EmbeddedResource Remove="Results\**" />
    <None Remove="AppContext\**" />
    <None Remove="Functional\**" />
    <None Remove="Mediator\**" />
    <None Remove="Results\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Results\Abstractions\ResultBaseTests.cs" />
    <Compile Include="Results\Abstractions\ResultLikeTests.cs" />
    <Compile Include="Results\ResultTestData.cs" />
    <Compile Include="Results\ResultTests.cs" />
    <Compile Include="Results\ResultTestUtility.cs" />
    <Compile Include="Results\ResultTTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CSharper\CSharper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
