name: Pull Request Tests

on:
  pull_request:
    branches:
      - main
      - develop  # Add other branches if needed

jobs:
  test:
    runs-on: windows-latest  # Required for net48

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
          # .NET Framework 4.8 SDK is pre-installed on windows-latest

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: |
          $TEST_PROJECTS = Get-ChildItem -Path tests -Filter "*.csproj" -Recurse
          if (-not $TEST_PROJECTS) {
            Write-Error "No test projects found in tests directory"
            exit 1
          }
          foreach ($PROJ in $TEST_PROJECTS) {
            Write-Host "Running tests for $PROJ"
            dotnet test $PROJ --configuration Release --no-build --verbosity normal --framework net48
            if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
            dotnet test $PROJ --configuration Release --no-build --verbosity normal --framework net8.0
            if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          }
        shell: pwsh  # PowerShell for better Windows scripting