name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test (e.g., main, feature/branch-name)'
        required: false
      log-mode:
        description: 'Test logging mode: detailed, minimal, or failed-only'
        required: false
        default: 'failed-only'
  workflow_call:
    inputs:
      branch:
        description: 'Branch to test (e.g., main, feature/branch-name)'
        required: false
        type: string
      log-mode:
        description: 'Test logging mode: detailed, minimal, or failed-only'
        required: false
        default: 'failed-only'
        type: string

jobs:
  main:
    runs-on: windows-latest  # Required for net48

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.event.inputs.branch || github.ref_name }}

      - name: Check installed SDKs
        id: check_sdks
        run: |
          # Check .NET Framework 4.8 SDK for net48 tests
          $net48Installed = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" -ErrorAction SilentlyContinue).Version -ge "4.8"
          if (-not $net48Installed) {
            Write-Host "NET Framework 4.8 SDK not found"
            "net48_installed=false" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          } else {
            Write-Host "NET Framework 4.8 SDK found"
            "net48_installed=true" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          }

          # Check .NET 8 SDK for net8.0 tests (any 8.0.x version)
          $dotnet8Installed = (dotnet --list-sdks | Select-String '^8\.0\.\d+') -ne $null
          if (-not $dotnet8Installed) {
            Write-Host "NET 8.0 SDK not found"
            "dotnet8_installed=false" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          } else {
            Write-Host "NET 8.0 SDK found"
            "dotnet8_installed=true" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Install .NET Framework 4.8 SDK
        if: steps.check_sdks.outputs.net48_installed != 'true'
        run: |
          Write-Host "Installing .NET Framework 4.8 SDK..."
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2088631" -OutFile "NDP48-DevPack-ENU.exe"
          Start-Process -FilePath "NDP48-DevPack-ENU.exe" -ArgumentList "/q /norestart" -Wait
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to install .NET Framework 4.8 SDK with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
          Write-Host ".NET Framework 4.8 SDK installed successfully"
        shell: pwsh

      - name: Setup .NET 8 SDK
        if: steps.check_sdks.outputs.dotnet8_installed != 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Try download build artifacts
        id: download_artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Restore dependencies
        if: steps.download_artifacts.outcome != 'success'
        run: dotnet restore
        shell: pwsh

      - name: Build
        if: steps.download_artifacts.outcome != 'success'
        run: dotnet build --configuration Release --no-restore
        shell: pwsh

      - name: Run unit tests
        run: |
          $TEST_PROJECTS = Get-ChildItem -Path tests -Filter "*.csproj" -Recurse
          if (-not $TEST_PROJECTS) {
            Write-Error "No test projects found in tests directory"
            exit 1
          }
          $LOG_MODE = "${{ inputs.log-mode || github.event.inputs.log-mode || 'failed-only' }}"
          foreach ($PROJ in $TEST_PROJECTS) {
            Write-Host "Running tests for $PROJ with log mode $LOG_MODE"
            if ($LOG_MODE -eq "failed-only") {
              $OUTPUT_FILE = "test-output-$($PROJ.BaseName).txt"
              dotnet test $PROJ --configuration Release --no-build --verbosity minimal --logger "console;verbosity=minimal" --settings tests/parallel.runsettings > $OUTPUT_FILE
              $EXIT_CODE = $LASTEXITCODE
              if ($EXIT_CODE -ne 0) {
                $FAILED_TESTS = Select-String -Path $OUTPUT_FILE -Pattern "Failed\s+.*" | ForEach-Object { $_.Line }
                if ($FAILED_TESTS) {
                  Write-Host "Failed tests for $PROJ (net48, net8.0):"
                  $FAILED_TESTS | ForEach-Object { Write-Host $_ }
                } else {
                  Write-Host "No failed tests for $PROJ (net48, net8.0), but exit code $EXIT_CODE indicates failure"
                  Get-Content $OUTPUT_FILE
                }
                exit 1
              } else {
                Write-Host "No failed tests for $PROJ (net48, net8.0)"
              }
            } elseif ($LOG_MODE -eq "minimal") {
              dotnet test $PROJ --configuration Release --no-build --verbosity minimal --settings tests/parallel.runsettings
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
            } else {
              dotnet test $PROJ --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed" --settings tests/parallel.runsettings
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
            }
          }
        shell: pwsh